services:
  rabbit:
    image: rabbitmq:4-management
    container_name: rabbit
    hostname: ${HOSTNAME_FQDN}
    environment:
      RABBITMQ_USE_LONGNAME: "true"
      RABBITMQ_NODENAME: "rabbit@${HOSTNAME_FQDN}"
      RABBITMQ_ERLANG_COOKIE: "RRKYXMQLSXURFZSUXFFU"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ../definitions.json:/etc/rabbitmq/definitions.json:ro
      - ../rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    ports:
      - "5672:5672"
      - "15672:15672"
      - "4369:4369"
      - "25672:25672" 
    restart: unless-stopped

volumes:
  rabbitmq_data: